name: Build and publish C++ packages

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc
          - clang
        version:
          - "10"
          - "11"
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
      # Install CMake
      - name: Install CMake
        run: |
          sudo apt-get update
      # Install dependencies
      - name: Install dependencies
        run: sudo apt-get install -y build-essential

      # Build the C++ project
      - name: Build project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      # Package the build artifacts
      - name: Package build artifacts
        run: |
          mkdir -p dist
          cp build/my_project_executable dist/
      - name: Install dependencies
        run: poetry install

      # Package the C++ project
      - name: Package project
        run: |
          cpack -G ZIP

      # Upload artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist/

  publish:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: https://pypi.org/p/deepcoder
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: package
          path: dist/

      - name: Publish packages to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
